apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: character-service-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
