apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eve-characterservice.fullname" . }}-database
  labels:
    {{- include "eve-characterservice.labels" . | nindent 4 }}
type: Opaque
data:
  DB_URL: {{ .Values.database.url | b64enc | quote}}