apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eve-characterservice.fullname" . }}-eve
  labels:
    {{- include "eve-characterservice.labels" . | nindent 4 }}
type: Opaque
data:
  URL: {{ .Values.eve.url | b64enc | quote}}
  CLIENT_ID: {{ .Values.eve.client_id | b64enc | quote}}
  CLIENT_SECRET: {{ .Values.eve.client_secret | b64enc | quote}}